// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocumentedEndpointResponse creates a new instance of MockDocumentedEndpointResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentedEndpointResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentedEndpointResponse {
	mock := &MockDocumentedEndpointResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocumentedEndpointResponse is an autogenerated mock type for the DocumentedEndpointResponse type
type MockDocumentedEndpointResponse struct {
	mock.Mock
}

type MockDocumentedEndpointResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentedEndpointResponse) EXPECT() *MockDocumentedEndpointResponse_Expecter {
	return &MockDocumentedEndpointResponse_Expecter{mock: &_m.Mock}
}

// GetMsg1 provides a mock function for the type MockDocumentedEndpointResponse
func (_mock *MockDocumentedEndpointResponse) GetMsg1() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMsg1")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDocumentedEndpointResponse_GetMsg1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMsg1'
type MockDocumentedEndpointResponse_GetMsg1_Call struct {
	*mock.Call
}

// GetMsg1 is a helper method to define mock.On call
func (_e *MockDocumentedEndpointResponse_Expecter) GetMsg1() *MockDocumentedEndpointResponse_GetMsg1_Call {
	return &MockDocumentedEndpointResponse_GetMsg1_Call{Call: _e.mock.On("GetMsg1")}
}

func (_c *MockDocumentedEndpointResponse_GetMsg1_Call) Run(run func()) *MockDocumentedEndpointResponse_GetMsg1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDocumentedEndpointResponse_GetMsg1_Call) Return(s string) *MockDocumentedEndpointResponse_GetMsg1_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDocumentedEndpointResponse_GetMsg1_Call) RunAndReturn(run func() string) *MockDocumentedEndpointResponse_GetMsg1_Call {
	_c.Call.Return(run)
	return _c
}

// GetMsgCode provides a mock function for the type MockDocumentedEndpointResponse
func (_mock *MockDocumentedEndpointResponse) GetMsgCode() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMsgCode")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDocumentedEndpointResponse_GetMsgCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMsgCode'
type MockDocumentedEndpointResponse_GetMsgCode_Call struct {
	*mock.Call
}

// GetMsgCode is a helper method to define mock.On call
func (_e *MockDocumentedEndpointResponse_Expecter) GetMsgCode() *MockDocumentedEndpointResponse_GetMsgCode_Call {
	return &MockDocumentedEndpointResponse_GetMsgCode_Call{Call: _e.mock.On("GetMsgCode")}
}

func (_c *MockDocumentedEndpointResponse_GetMsgCode_Call) Run(run func()) *MockDocumentedEndpointResponse_GetMsgCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDocumentedEndpointResponse_GetMsgCode_Call) Return(s string) *MockDocumentedEndpointResponse_GetMsgCode_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDocumentedEndpointResponse_GetMsgCode_Call) RunAndReturn(run func() string) *MockDocumentedEndpointResponse_GetMsgCode_Call {
	_c.Call.Return(run)
	return _c
}

// IsSuccess provides a mock function for the type MockDocumentedEndpointResponse
func (_mock *MockDocumentedEndpointResponse) IsSuccess() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsSuccess")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDocumentedEndpointResponse_IsSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSuccess'
type MockDocumentedEndpointResponse_IsSuccess_Call struct {
	*mock.Call
}

// IsSuccess is a helper method to define mock.On call
func (_e *MockDocumentedEndpointResponse_Expecter) IsSuccess() *MockDocumentedEndpointResponse_IsSuccess_Call {
	return &MockDocumentedEndpointResponse_IsSuccess_Call{Call: _e.mock.On("IsSuccess")}
}

func (_c *MockDocumentedEndpointResponse_IsSuccess_Call) Run(run func()) *MockDocumentedEndpointResponse_IsSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDocumentedEndpointResponse_IsSuccess_Call) Return(b bool) *MockDocumentedEndpointResponse_IsSuccess_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDocumentedEndpointResponse_IsSuccess_Call) RunAndReturn(run func() bool) *MockDocumentedEndpointResponse_IsSuccess_Call {
	_c.Call.Return(run)
	return _c
}
