// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/krsec/pkg/broker"
	"github.com/smallfish06/krsec/pkg/ls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Authenticate(ctx context.Context, creds broker.Credentials) (*broker.Token, error) {
	ret := _mock.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *broker.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) (*broker.Token, error)); ok {
		return returnFunc(ctx, creds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) *broker.Token); ok {
		r0 = returnFunc(ctx, creds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.Credentials) error); ok {
		r1 = returnFunc(ctx, creds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAdapter_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - creds broker.Credentials
func (_e *MockAdapter_Expecter) Authenticate(ctx interface{}, creds interface{}) *MockAdapter_Authenticate_Call {
	return &MockAdapter_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, creds)}
}

func (_c *MockAdapter_Authenticate_Call) Run(run func(ctx context.Context, creds broker.Credentials)) *MockAdapter_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Credentials
		if args[1] != nil {
			arg1 = args[1].(broker.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_Authenticate_Call) Return(token *broker.Token, err error) *MockAdapter_Authenticate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAdapter_Authenticate_Call) RunAndReturn(run func(ctx context.Context, creds broker.Credentials) (*broker.Token, error)) *MockAdapter_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// BuildOverseasTradeSubscriptions provides a mock function for the type MockAdapter
func (_mock *MockAdapter) BuildOverseasTradeSubscriptions(ctx context.Context, market string, maxRows int) ([]ls.RealtimeSubscription, error) {
	ret := _mock.Called(ctx, market, maxRows)

	if len(ret) == 0 {
		panic("no return value specified for BuildOverseasTradeSubscriptions")
	}

	var r0 []ls.RealtimeSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]ls.RealtimeSubscription, error)); ok {
		return returnFunc(ctx, market, maxRows)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []ls.RealtimeSubscription); ok {
		r0 = returnFunc(ctx, market, maxRows)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ls.RealtimeSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, market, maxRows)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_BuildOverseasTradeSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildOverseasTradeSubscriptions'
type MockAdapter_BuildOverseasTradeSubscriptions_Call struct {
	*mock.Call
}

// BuildOverseasTradeSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - maxRows int
func (_e *MockAdapter_Expecter) BuildOverseasTradeSubscriptions(ctx interface{}, market interface{}, maxRows interface{}) *MockAdapter_BuildOverseasTradeSubscriptions_Call {
	return &MockAdapter_BuildOverseasTradeSubscriptions_Call{Call: _e.mock.On("BuildOverseasTradeSubscriptions", ctx, market, maxRows)}
}

func (_c *MockAdapter_BuildOverseasTradeSubscriptions_Call) Run(run func(ctx context.Context, market string, maxRows int)) *MockAdapter_BuildOverseasTradeSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_BuildOverseasTradeSubscriptions_Call) Return(vs []ls.RealtimeSubscription, err error) *MockAdapter_BuildOverseasTradeSubscriptions_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockAdapter_BuildOverseasTradeSubscriptions_Call) RunAndReturn(run func(ctx context.Context, market string, maxRows int) ([]ls.RealtimeSubscription, error)) *MockAdapter_BuildOverseasTradeSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// BuildTradeSubscriptions provides a mock function for the type MockAdapter
func (_mock *MockAdapter) BuildTradeSubscriptions(ctx context.Context) ([]ls.RealtimeSubscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuildTradeSubscriptions")
	}

	var r0 []ls.RealtimeSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ls.RealtimeSubscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ls.RealtimeSubscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ls.RealtimeSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_BuildTradeSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildTradeSubscriptions'
type MockAdapter_BuildTradeSubscriptions_Call struct {
	*mock.Call
}

// BuildTradeSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdapter_Expecter) BuildTradeSubscriptions(ctx interface{}) *MockAdapter_BuildTradeSubscriptions_Call {
	return &MockAdapter_BuildTradeSubscriptions_Call{Call: _e.mock.On("BuildTradeSubscriptions", ctx)}
}

func (_c *MockAdapter_BuildTradeSubscriptions_Call) Run(run func(ctx context.Context)) *MockAdapter_BuildTradeSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_BuildTradeSubscriptions_Call) Return(vs []ls.RealtimeSubscription, err error) *MockAdapter_BuildTradeSubscriptions_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockAdapter_BuildTradeSubscriptions_Call) RunAndReturn(run func(ctx context.Context) ([]ls.RealtimeSubscription, error)) *MockAdapter_BuildTradeSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// CallEndpoint provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CallEndpoint(ctx context.Context, method string, path string, trCD string, request any) (any, error) {
	ret := _mock.Called(ctx, method, path, trCD, request)

	if len(ret) == 0 {
		panic("no return value specified for CallEndpoint")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any) (any, error)); ok {
		return returnFunc(ctx, method, path, trCD, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any) any); ok {
		r0 = returnFunc(ctx, method, path, trCD, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, any) error); ok {
		r1 = returnFunc(ctx, method, path, trCD, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_CallEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEndpoint'
type MockAdapter_CallEndpoint_Call struct {
	*mock.Call
}

// CallEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - trCD string
//   - request any
func (_e *MockAdapter_Expecter) CallEndpoint(ctx interface{}, method interface{}, path interface{}, trCD interface{}, request interface{}) *MockAdapter_CallEndpoint_Call {
	return &MockAdapter_CallEndpoint_Call{Call: _e.mock.On("CallEndpoint", ctx, method, path, trCD, request)}
}

func (_c *MockAdapter_CallEndpoint_Call) Run(run func(ctx context.Context, method string, path string, trCD string, request any)) *MockAdapter_CallEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAdapter_CallEndpoint_Call) Return(v any, err error) *MockAdapter_CallEndpoint_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAdapter_CallEndpoint_Call) RunAndReturn(run func(ctx context.Context, method string, path string, trCD string, request any) (any, error)) *MockAdapter_CallEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CancelOrder provides a mock function for the type MockAdapter
func (_mock *MockAdapter) CancelOrder(ctx context.Context, orderID string) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockAdapter_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockAdapter_Expecter) CancelOrder(ctx interface{}, orderID interface{}) *MockAdapter_CancelOrder_Call {
	return &MockAdapter_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderID)}
}

func (_c *MockAdapter_CancelOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockAdapter_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_CancelOrder_Call) Return(err error) *MockAdapter_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) error) *MockAdapter_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectRealtime provides a mock function for the type MockAdapter
func (_mock *MockAdapter) ConnectRealtime(ctx context.Context) (*ls.RealtimeConn, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ConnectRealtime")
	}

	var r0 *ls.RealtimeConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ls.RealtimeConn, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ls.RealtimeConn); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ls.RealtimeConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_ConnectRealtime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectRealtime'
type MockAdapter_ConnectRealtime_Call struct {
	*mock.Call
}

// ConnectRealtime is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdapter_Expecter) ConnectRealtime(ctx interface{}) *MockAdapter_ConnectRealtime_Call {
	return &MockAdapter_ConnectRealtime_Call{Call: _e.mock.On("ConnectRealtime", ctx)}
}

func (_c *MockAdapter_ConnectRealtime_Call) Run(run func(ctx context.Context)) *MockAdapter_ConnectRealtime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdapter_ConnectRealtime_Call) Return(v *ls.RealtimeConn, err error) *MockAdapter_ConnectRealtime_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAdapter_ConnectRealtime_Call) RunAndReturn(run func(ctx context.Context) (*ls.RealtimeConn, error)) *MockAdapter_ConnectRealtime_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetBalance(ctx context.Context, accountID string) (*broker.Balance, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *broker.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.Balance, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.Balance); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockAdapter_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockAdapter_Expecter) GetBalance(ctx interface{}, accountID interface{}) *MockAdapter_GetBalance_Call {
	return &MockAdapter_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountID)}
}

func (_c *MockAdapter_GetBalance_Call) Run(run func(ctx context.Context, accountID string)) *MockAdapter_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_GetBalance_Call) Return(balance *broker.Balance, err error) *MockAdapter_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockAdapter_GetBalance_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*broker.Balance, error)) *MockAdapter_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrument provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetInstrument(ctx context.Context, market string, symbol string) (*broker.Instrument, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrument")
	}

	var r0 *broker.Instrument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Instrument, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Instrument); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Instrument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetInstrument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrument'
type MockAdapter_GetInstrument_Call struct {
	*mock.Call
}

// GetInstrument is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockAdapter_Expecter) GetInstrument(ctx interface{}, market interface{}, symbol interface{}) *MockAdapter_GetInstrument_Call {
	return &MockAdapter_GetInstrument_Call{Call: _e.mock.On("GetInstrument", ctx, market, symbol)}
}

func (_c *MockAdapter_GetInstrument_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockAdapter_GetInstrument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_GetInstrument_Call) Return(instrument *broker.Instrument, err error) *MockAdapter_GetInstrument_Call {
	_c.Call.Return(instrument, err)
	return _c
}

func (_c *MockAdapter_GetInstrument_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Instrument, error)) *MockAdapter_GetInstrument_Call {
	_c.Call.Return(run)
	return _c
}

// GetOHLCV provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetOHLCV(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error) {
	ret := _mock.Called(ctx, market, symbol, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetOHLCV")
	}

	var r0 []broker.OHLCV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) ([]broker.OHLCV, error)); ok {
		return returnFunc(ctx, market, symbol, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) []broker.OHLCV); ok {
		r0 = returnFunc(ctx, market, symbol, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OHLCV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, broker.OHLCVOpts) error); ok {
		r1 = returnFunc(ctx, market, symbol, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetOHLCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOHLCV'
type MockAdapter_GetOHLCV_Call struct {
	*mock.Call
}

// GetOHLCV is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
//   - opts broker.OHLCVOpts
func (_e *MockAdapter_Expecter) GetOHLCV(ctx interface{}, market interface{}, symbol interface{}, opts interface{}) *MockAdapter_GetOHLCV_Call {
	return &MockAdapter_GetOHLCV_Call{Call: _e.mock.On("GetOHLCV", ctx, market, symbol, opts)}
}

func (_c *MockAdapter_GetOHLCV_Call) Run(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts)) *MockAdapter_GetOHLCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 broker.OHLCVOpts
		if args[3] != nil {
			arg3 = args[3].(broker.OHLCVOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_GetOHLCV_Call) Return(oHLCVs []broker.OHLCV, err error) *MockAdapter_GetOHLCV_Call {
	_c.Call.Return(oHLCVs, err)
	return _c
}

func (_c *MockAdapter_GetOHLCV_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error)) *MockAdapter_GetOHLCV_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetOrder(ctx context.Context, orderID string) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockAdapter_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockAdapter_Expecter) GetOrder(ctx interface{}, orderID interface{}) *MockAdapter_GetOrder_Call {
	return &MockAdapter_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *MockAdapter_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockAdapter_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_GetOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockAdapter_GetOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockAdapter_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*broker.OrderResult, error)) *MockAdapter_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderFills provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetOrderFills(ctx context.Context, orderID string) ([]broker.OrderFill, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderFills")
	}

	var r0 []broker.OrderFill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.OrderFill, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.OrderFill); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OrderFill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetOrderFills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderFills'
type MockAdapter_GetOrderFills_Call struct {
	*mock.Call
}

// GetOrderFills is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockAdapter_Expecter) GetOrderFills(ctx interface{}, orderID interface{}) *MockAdapter_GetOrderFills_Call {
	return &MockAdapter_GetOrderFills_Call{Call: _e.mock.On("GetOrderFills", ctx, orderID)}
}

func (_c *MockAdapter_GetOrderFills_Call) Run(run func(ctx context.Context, orderID string)) *MockAdapter_GetOrderFills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_GetOrderFills_Call) Return(orderFills []broker.OrderFill, err error) *MockAdapter_GetOrderFills_Call {
	_c.Call.Return(orderFills, err)
	return _c
}

func (_c *MockAdapter_GetOrderFills_Call) RunAndReturn(run func(ctx context.Context, orderID string) ([]broker.OrderFill, error)) *MockAdapter_GetOrderFills_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositions provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetPositions(ctx context.Context, accountID string) ([]broker.Position, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPositions")
	}

	var r0 []broker.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.Position, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.Position); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositions'
type MockAdapter_GetPositions_Call struct {
	*mock.Call
}

// GetPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockAdapter_Expecter) GetPositions(ctx interface{}, accountID interface{}) *MockAdapter_GetPositions_Call {
	return &MockAdapter_GetPositions_Call{Call: _e.mock.On("GetPositions", ctx, accountID)}
}

func (_c *MockAdapter_GetPositions_Call) Run(run func(ctx context.Context, accountID string)) *MockAdapter_GetPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_GetPositions_Call) Return(positions []broker.Position, err error) *MockAdapter_GetPositions_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockAdapter_GetPositions_Call) RunAndReturn(run func(ctx context.Context, accountID string) ([]broker.Position, error)) *MockAdapter_GetPositions_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function for the type MockAdapter
func (_mock *MockAdapter) GetQuote(ctx context.Context, market string, symbol string) (*broker.Quote, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *broker.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Quote, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Quote); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockAdapter_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockAdapter_Expecter) GetQuote(ctx interface{}, market interface{}, symbol interface{}) *MockAdapter_GetQuote_Call {
	return &MockAdapter_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, market, symbol)}
}

func (_c *MockAdapter_GetQuote_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockAdapter_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_GetQuote_Call) Return(quote *broker.Quote, err error) *MockAdapter_GetQuote_Call {
	_c.Call.Return(quote, err)
	return _c
}

func (_c *MockAdapter_GetQuote_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Quote, error)) *MockAdapter_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyOrder provides a mock function for the type MockAdapter
func (_mock *MockAdapter) ModifyOrder(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for ModifyOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, broker.ModifyOrderRequest) error); ok {
		r1 = returnFunc(ctx, orderID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_ModifyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyOrder'
type MockAdapter_ModifyOrder_Call struct {
	*mock.Call
}

// ModifyOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - req broker.ModifyOrderRequest
func (_e *MockAdapter_Expecter) ModifyOrder(ctx interface{}, orderID interface{}, req interface{}) *MockAdapter_ModifyOrder_Call {
	return &MockAdapter_ModifyOrder_Call{Call: _e.mock.On("ModifyOrder", ctx, orderID, req)}
}

func (_c *MockAdapter_ModifyOrder_Call) Run(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest)) *MockAdapter_ModifyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 broker.ModifyOrderRequest
		if args[2] != nil {
			arg2 = args[2].(broker.ModifyOrderRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_ModifyOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockAdapter_ModifyOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockAdapter_ModifyOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error)) *MockAdapter_ModifyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAdapter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockAdapter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) Name() *MockAdapter_Name_Call {
	return &MockAdapter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockAdapter_Name_Call) Run(run func()) *MockAdapter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_Name_Call) Return(s string) *MockAdapter_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAdapter_Name_Call) RunAndReturn(run func() string) *MockAdapter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function for the type MockAdapter
func (_mock *MockAdapter) PlaceOrder(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.OrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockAdapter_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req broker.OrderRequest
func (_e *MockAdapter_Expecter) PlaceOrder(ctx interface{}, req interface{}) *MockAdapter_PlaceOrder_Call {
	return &MockAdapter_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, req)}
}

func (_c *MockAdapter_PlaceOrder_Call) Run(run func(ctx context.Context, req broker.OrderRequest)) *MockAdapter_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.OrderRequest
		if args[1] != nil {
			arg1 = args[1].(broker.OrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_PlaceOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockAdapter_PlaceOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockAdapter_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error)) *MockAdapter_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}
