// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockjsonNumber creates a new instance of MockjsonNumber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockjsonNumber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockjsonNumber {
	mock := &MockjsonNumber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockjsonNumber is an autogenerated mock type for the jsonNumber type
type MockjsonNumber struct {
	mock.Mock
}

type MockjsonNumber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockjsonNumber) EXPECT() *MockjsonNumber_Expecter {
	return &MockjsonNumber_Expecter{mock: &_m.Mock}
}

// String provides a mock function for the type MockjsonNumber
func (_mock *MockjsonNumber) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockjsonNumber_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockjsonNumber_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockjsonNumber_Expecter) String() *MockjsonNumber_String_Call {
	return &MockjsonNumber_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockjsonNumber_String_Call) Run(run func()) *MockjsonNumber_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockjsonNumber_String_Call) Return(s string) *MockjsonNumber_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockjsonNumber_String_Call) RunAndReturn(run func() string) *MockjsonNumber_String_Call {
	_c.Call.Return(run)
	return _c
}
