// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// DeleteToken provides a mock function for the type MockManager
func (_mock *MockManager) DeleteToken(appKey string) error {
	ret := _mock.Called(appKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(appKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type MockManager_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - appKey string
func (_e *MockManager_Expecter) DeleteToken(appKey interface{}) *MockManager_DeleteToken_Call {
	return &MockManager_DeleteToken_Call{Call: _e.mock.On("DeleteToken", appKey)}
}

func (_c *MockManager_DeleteToken_Call) Run(run func(appKey string)) *MockManager_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_DeleteToken_Call) Return(err error) *MockManager_DeleteToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_DeleteToken_Call) RunAndReturn(run func(appKey string) error) *MockManager_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type MockManager
func (_mock *MockManager) GetToken(appKey string) (string, time.Time, bool) {
	ret := _mock.Called(appKey)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 time.Time
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, time.Time, bool)); ok {
		return returnFunc(appKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(appKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) time.Time); ok {
		r1 = returnFunc(appKey)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(string) bool); ok {
		r2 = returnFunc(appKey)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockManager_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockManager_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - appKey string
func (_e *MockManager_Expecter) GetToken(appKey interface{}) *MockManager_GetToken_Call {
	return &MockManager_GetToken_Call{Call: _e.mock.On("GetToken", appKey)}
}

func (_c *MockManager_GetToken_Call) Run(run func(appKey string)) *MockManager_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetToken_Call) Return(s string, time1 time.Time, b bool) *MockManager_GetToken_Call {
	_c.Call.Return(s, time1, b)
	return _c
}

func (_c *MockManager_GetToken_Call) RunAndReturn(run func(appKey string) (string, time.Time, bool)) *MockManager_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetToken provides a mock function for the type MockManager
func (_mock *MockManager) SetToken(appKey string, token string, expiresAt time.Time) error {
	ret := _mock.Called(appKey, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Time) error); ok {
		r0 = returnFunc(appKey, token, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type MockManager_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - appKey string
//   - token string
//   - expiresAt time.Time
func (_e *MockManager_Expecter) SetToken(appKey interface{}, token interface{}, expiresAt interface{}) *MockManager_SetToken_Call {
	return &MockManager_SetToken_Call{Call: _e.mock.On("SetToken", appKey, token, expiresAt)}
}

func (_c *MockManager_SetToken_Call) Run(run func(appKey string, token string, expiresAt time.Time)) *MockManager_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_SetToken_Call) Return(err error) *MockManager_SetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_SetToken_Call) RunAndReturn(run func(appKey string, token string, expiresAt time.Time) error) *MockManager_SetToken_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForAuth provides a mock function for the type MockManager
func (_mock *MockManager) WaitForAuth(appKey string) {
	_mock.Called(appKey)
	return
}

// MockManager_WaitForAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForAuth'
type MockManager_WaitForAuth_Call struct {
	*mock.Call
}

// WaitForAuth is a helper method to define mock.On call
//   - appKey string
func (_e *MockManager_Expecter) WaitForAuth(appKey interface{}) *MockManager_WaitForAuth_Call {
	return &MockManager_WaitForAuth_Call{Call: _e.mock.On("WaitForAuth", appKey)}
}

func (_c *MockManager_WaitForAuth_Call) Run(run func(appKey string)) *MockManager_WaitForAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_WaitForAuth_Call) Return() *MockManager_WaitForAuth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_WaitForAuth_Call) RunAndReturn(run func(appKey string)) *MockManager_WaitForAuth_Call {
	_c.Run(run)
	return _c
}
