// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMocklsEndpointCaller creates a new instance of MocklsEndpointCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklsEndpointCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocklsEndpointCaller {
	mock := &MocklsEndpointCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocklsEndpointCaller is an autogenerated mock type for the lsEndpointCaller type
type MocklsEndpointCaller struct {
	mock.Mock
}

type MocklsEndpointCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MocklsEndpointCaller) EXPECT() *MocklsEndpointCaller_Expecter {
	return &MocklsEndpointCaller_Expecter{mock: &_m.Mock}
}

// CallEndpoint provides a mock function for the type MocklsEndpointCaller
func (_mock *MocklsEndpointCaller) CallEndpoint(ctx context.Context, method string, path string, trCD string, request any) (any, error) {
	ret := _mock.Called(ctx, method, path, trCD, request)

	if len(ret) == 0 {
		panic("no return value specified for CallEndpoint")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any) (any, error)); ok {
		return returnFunc(ctx, method, path, trCD, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any) any); ok {
		r0 = returnFunc(ctx, method, path, trCD, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, any) error); ok {
		r1 = returnFunc(ctx, method, path, trCD, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocklsEndpointCaller_CallEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEndpoint'
type MocklsEndpointCaller_CallEndpoint_Call struct {
	*mock.Call
}

// CallEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - trCD string
//   - request any
func (_e *MocklsEndpointCaller_Expecter) CallEndpoint(ctx interface{}, method interface{}, path interface{}, trCD interface{}, request interface{}) *MocklsEndpointCaller_CallEndpoint_Call {
	return &MocklsEndpointCaller_CallEndpoint_Call{Call: _e.mock.On("CallEndpoint", ctx, method, path, trCD, request)}
}

func (_c *MocklsEndpointCaller_CallEndpoint_Call) Run(run func(ctx context.Context, method string, path string, trCD string, request any)) *MocklsEndpointCaller_CallEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MocklsEndpointCaller_CallEndpoint_Call) Return(v any, err error) *MocklsEndpointCaller_CallEndpoint_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MocklsEndpointCaller_CallEndpoint_Call) RunAndReturn(run func(ctx context.Context, method string, path string, trCD string, request any) (any, error)) *MocklsEndpointCaller_CallEndpoint_Call {
	_c.Call.Return(run)
	return _c
}
