// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockqueryReader creates a new instance of MockqueryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockqueryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockqueryReader {
	mock := &MockqueryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockqueryReader is an autogenerated mock type for the queryReader type
type MockqueryReader struct {
	mock.Mock
}

type MockqueryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockqueryReader) EXPECT() *MockqueryReader_Expecter {
	return &MockqueryReader_Expecter{mock: &_m.Mock}
}

// QueryParam provides a mock function for the type MockqueryReader
func (_mock *MockqueryReader) QueryParam(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for QueryParam")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockqueryReader_QueryParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryParam'
type MockqueryReader_QueryParam_Call struct {
	*mock.Call
}

// QueryParam is a helper method to define mock.On call
//   - name string
func (_e *MockqueryReader_Expecter) QueryParam(name interface{}) *MockqueryReader_QueryParam_Call {
	return &MockqueryReader_QueryParam_Call{Call: _e.mock.On("QueryParam", name)}
}

func (_c *MockqueryReader_QueryParam_Call) Run(run func(name string)) *MockqueryReader_QueryParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockqueryReader_QueryParam_Call) Return(s string) *MockqueryReader_QueryParam_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockqueryReader_QueryParam_Call) RunAndReturn(run func(name string) string) *MockqueryReader_QueryParam_Call {
	_c.Call.Return(run)
	return _c
}
