// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMocktossEndpointCaller creates a new instance of MocktossEndpointCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktossEndpointCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktossEndpointCaller {
	mock := &MocktossEndpointCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocktossEndpointCaller is an autogenerated mock type for the tossEndpointCaller type
type MocktossEndpointCaller struct {
	mock.Mock
}

type MocktossEndpointCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktossEndpointCaller) EXPECT() *MocktossEndpointCaller_Expecter {
	return &MocktossEndpointCaller_Expecter{mock: &_m.Mock}
}

// CallEndpoint provides a mock function for the type MocktossEndpointCaller
func (_mock *MocktossEndpointCaller) CallEndpoint(ctx context.Context, method string, path string, query map[string]any, body any) (any, error) {
	ret := _mock.Called(ctx, method, path, query, body)

	if len(ret) == 0 {
		panic("no return value specified for CallEndpoint")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any, any) (any, error)); ok {
		return returnFunc(ctx, method, path, query, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any, any) any); ok {
		r0 = returnFunc(ctx, method, path, query, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, map[string]any, any) error); ok {
		r1 = returnFunc(ctx, method, path, query, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocktossEndpointCaller_CallEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEndpoint'
type MocktossEndpointCaller_CallEndpoint_Call struct {
	*mock.Call
}

// CallEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - query map[string]any
//   - body any
func (_e *MocktossEndpointCaller_Expecter) CallEndpoint(ctx interface{}, method interface{}, path interface{}, query interface{}, body interface{}) *MocktossEndpointCaller_CallEndpoint_Call {
	return &MocktossEndpointCaller_CallEndpoint_Call{Call: _e.mock.On("CallEndpoint", ctx, method, path, query, body)}
}

func (_c *MocktossEndpointCaller_CallEndpoint_Call) Run(run func(ctx context.Context, method string, path string, query map[string]any, body any)) *MocktossEndpointCaller_CallEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MocktossEndpointCaller_CallEndpoint_Call) Return(v any, err error) *MocktossEndpointCaller_CallEndpoint_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MocktossEndpointCaller_CallEndpoint_Call) RunAndReturn(run func(ctx context.Context, method string, path string, query map[string]any, body any) (any, error)) *MocktossEndpointCaller_CallEndpoint_Call {
	_c.Call.Return(run)
	return _c
}
